name: gh_deploy
on:
  pull_request:
    branches:
      - dev
      - main
      - "!docs/**"
  push:
    branches:
      - dev
      - main

permissions:
  contents: write

jobs:
  gh_build_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install packages
        run: |
          pnpm install
          pnpm build:github-pages

      - name: Deploy Build dist
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npx gh-pages -d dist --repo https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
